// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/terms": {
    params: {};
  };
  "/company": {
    params: {};
  };
  "/request-invite": {
    params: {};
  };
  "/onboarding": {
    params: {};
  };
  "/cli/authorize": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/environments/new": {
    params: {};
  };
  "/environments/:id/settings": {
    params: {
      "id": string;
    };
  };
  "/environments/:id/deploys": {
    params: {
      "id": string;
    };
  };
  "/environments/:id/tasks/:taskId": {
    params: {
      "id": string;
      "taskId": string;
    };
  };
  "/settings": {
    params: {};
  };
  "/data": {
    params: {};
  };
  "/billing": {
    params: {};
  };
  "/inbox": {
    params: {};
  };
  "/tasks": {
    params: {};
  };
  "/sessions": {
    params: {};
  };
  "/teams": {
    params: {};
  };
  "/projects/:id": {
    params: {
      "id": string;
    };
  };
  "/api/auth/invite": {
    params: {};
  };
  "/api/auth/login/:provider": {
    params: {
      "provider": string;
    };
  };
  "/api/auth/callback/:provider": {
    params: {
      "provider": string;
    };
  };
  "/api/auth/me": {
    params: {};
  };
  "/api/auth/profile": {
    params: {};
  };
  "/api/auth/logout": {
    params: {};
  };
  "/api/auth/tokens": {
    params: {};
  };
  "/api/orgs": {
    params: {};
  };
  "/api/orgs/members": {
    params: {};
  };
  "/api/projects": {
    params: {};
  };
  "/api/projects/:id/tasks": {
    params: {
      "id": string;
    };
  };
  "/api/projects/:id/tasks/:taskId": {
    params: {
      "id": string;
      "taskId": string;
    };
  };
  "/api/projects/:id/tasks/:taskId/merge": {
    params: {
      "id": string;
      "taskId": string;
    };
  };
  "/api/projects/:id/tasks/:taskId/cancel": {
    params: {
      "id": string;
      "taskId": string;
    };
  };
  "/api/projects/:id/tasks/:taskId/attachments": {
    params: {
      "id": string;
      "taskId": string;
    };
  };
  "/api/environments": {
    params: {};
  };
  "/api/environments/sync": {
    params: {};
  };
  "/api/environments/:id": {
    params: {
      "id": string;
    };
  };
  "/api/environments/:id/claude": {
    params: {
      "id": string;
    };
  };
  "/api/environments/:id/secrets": {
    params: {
      "id": string;
    };
  };
  "/api/environments/:id/vercel-sync": {
    params: {
      "id": string;
    };
  };
  "/api/environments/:id/sandbox": {
    params: {
      "id": string;
    };
  };
  "/api/sandbox/callback": {
    params: {};
  };
  "/api/environments/:id/workspaces/:workspaceId/logs": {
    params: {
      "id": string;
      "workspaceId": string;
    };
  };
  "/api/databases": {
    params: {};
  };
  "/api/environments/:id/status": {
    params: {
      "id": string;
    };
  };
  "/api/environments/:id/tasks": {
    params: {
      "id": string;
    };
  };
  "/api/environments/:id/tasks/:taskId": {
    params: {
      "id": string;
      "taskId": string;
    };
  };
  "/api/environments/:id/tasks/:taskId/merge": {
    params: {
      "id": string;
      "taskId": string;
    };
  };
  "/api/environments/:id/tasks/:taskId/cancel": {
    params: {
      "id": string;
      "taskId": string;
    };
  };
  "/api/environments/:id/tasks/:taskId/delete": {
    params: {
      "id": string;
      "taskId": string;
    };
  };
  "/api/environments/:id/tasks/:taskId/attachments": {
    params: {
      "id": string;
      "taskId": string;
    };
  };
  "/api/tasks": {
    params: {};
  };
  "/api/environments/:id/deployments": {
    params: {
      "id": string;
    };
  };
  "/api/vercel/environments": {
    params: {};
  };
  "/api/github/repos": {
    params: {};
  };
  "/api/integrations/github/start": {
    params: {};
  };
  "/api/integrations/github": {
    params: {};
  };
  "/api/integrations/vercel/start": {
    params: {};
  };
  "/api/integrations/vercel/callback": {
    params: {};
  };
  "/api/integrations/vercel": {
    params: {};
  };
  "/api/integrations/status": {
    params: {};
  };
  "/api/claude-key": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/privacy" | "/terms" | "/company" | "/request-invite" | "/onboarding" | "/cli/authorize" | "/dashboard" | "/environments/new" | "/environments/:id/settings" | "/environments/:id/deploys" | "/environments/:id/tasks/:taskId" | "/settings" | "/data" | "/billing" | "/inbox" | "/tasks" | "/sessions" | "/teams" | "/projects/:id" | "/api/auth/invite" | "/api/auth/login/:provider" | "/api/auth/callback/:provider" | "/api/auth/me" | "/api/auth/profile" | "/api/auth/logout" | "/api/auth/tokens" | "/api/orgs" | "/api/orgs/members" | "/api/projects" | "/api/projects/:id/tasks" | "/api/projects/:id/tasks/:taskId" | "/api/projects/:id/tasks/:taskId/merge" | "/api/projects/:id/tasks/:taskId/cancel" | "/api/projects/:id/tasks/:taskId/attachments" | "/api/environments" | "/api/environments/sync" | "/api/environments/:id" | "/api/environments/:id/claude" | "/api/environments/:id/secrets" | "/api/environments/:id/vercel-sync" | "/api/environments/:id/sandbox" | "/api/sandbox/callback" | "/api/environments/:id/workspaces/:workspaceId/logs" | "/api/databases" | "/api/environments/:id/status" | "/api/environments/:id/tasks" | "/api/environments/:id/tasks/:taskId" | "/api/environments/:id/tasks/:taskId/merge" | "/api/environments/:id/tasks/:taskId/cancel" | "/api/environments/:id/tasks/:taskId/delete" | "/api/environments/:id/tasks/:taskId/attachments" | "/api/tasks" | "/api/environments/:id/deployments" | "/api/vercel/environments" | "/api/github/repos" | "/api/integrations/github/start" | "/api/integrations/github" | "/api/integrations/vercel/start" | "/api/integrations/vercel/callback" | "/api/integrations/vercel" | "/api/integrations/status" | "/api/claude-key";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/privacy.tsx": {
    id: "routes/privacy";
    page: "/privacy";
  };
  "routes/terms.tsx": {
    id: "routes/terms";
    page: "/terms";
  };
  "routes/company.tsx": {
    id: "routes/company";
    page: "/company";
  };
  "routes/early-access.tsx": {
    id: "routes/early-access";
    page: "/request-invite";
  };
  "routes/onboarding.tsx": {
    id: "routes/onboarding";
    page: "/onboarding";
  };
  "routes/cli.authorize.tsx": {
    id: "routes/cli.authorize";
    page: "/cli/authorize";
  };
  "routes/_auth.tsx": {
    id: "routes/_auth";
    page: "/dashboard" | "/environments/new" | "/environments/:id/settings" | "/environments/:id/deploys" | "/environments/:id/tasks/:taskId" | "/settings" | "/data" | "/billing" | "/inbox" | "/tasks" | "/sessions" | "/teams" | "/projects/:id";
  };
  "routes/_auth.environments.tsx": {
    id: "routes/_auth.environments";
    page: "/dashboard";
  };
  "routes/_auth.environments.new.tsx": {
    id: "routes/_auth.environments.new";
    page: "/environments/new";
  };
  "routes/_auth.environments.$id_.settings.tsx": {
    id: "routes/_auth.environments.$id_.settings";
    page: "/environments/:id/settings";
  };
  "routes/_auth.environments.$id_.deploys.tsx": {
    id: "routes/_auth.environments.$id_.deploys";
    page: "/environments/:id/deploys";
  };
  "routes/_auth.environments.$id_.tasks.$taskId.tsx": {
    id: "routes/_auth.environments.$id_.tasks.$taskId";
    page: "/environments/:id/tasks/:taskId";
  };
  "routes/_auth.settings.tsx": {
    id: "routes/_auth.settings";
    page: "/settings";
  };
  "routes/_auth.data.tsx": {
    id: "routes/_auth.data";
    page: "/data";
  };
  "routes/_auth.billing.tsx": {
    id: "routes/_auth.billing";
    page: "/billing";
  };
  "routes/_auth.inbox.tsx": {
    id: "routes/_auth.inbox";
    page: "/inbox";
  };
  "routes/_auth.tasks.tsx": {
    id: "routes/_auth.tasks";
    page: "/tasks";
  };
  "routes/_auth.sessions.tsx": {
    id: "routes/_auth.sessions";
    page: "/sessions";
  };
  "routes/_auth.teams.tsx": {
    id: "routes/_auth.teams";
    page: "/teams";
  };
  "routes/_auth.projects.$id.tsx": {
    id: "routes/_auth.projects.$id";
    page: "/projects/:id";
  };
  "routes/api.auth.invite.ts": {
    id: "routes/api.auth.invite";
    page: "/api/auth/invite";
  };
  "routes/api.auth.login.$provider.ts": {
    id: "routes/api.auth.login.$provider";
    page: "/api/auth/login/:provider";
  };
  "routes/api.auth.callback.$provider.ts": {
    id: "routes/api.auth.callback.$provider";
    page: "/api/auth/callback/:provider";
  };
  "routes/api.auth.me.ts": {
    id: "routes/api.auth.me";
    page: "/api/auth/me";
  };
  "routes/api.auth.profile.ts": {
    id: "routes/api.auth.profile";
    page: "/api/auth/profile";
  };
  "routes/api.auth.logout.ts": {
    id: "routes/api.auth.logout";
    page: "/api/auth/logout";
  };
  "routes/api.auth.tokens.ts": {
    id: "routes/api.auth.tokens";
    page: "/api/auth/tokens";
  };
  "routes/api.orgs.ts": {
    id: "routes/api.orgs";
    page: "/api/orgs";
  };
  "routes/api.orgs.members.ts": {
    id: "routes/api.orgs.members";
    page: "/api/orgs/members";
  };
  "routes/api.projects.ts": {
    id: "routes/api.projects";
    page: "/api/projects";
  };
  "routes/api.projects.$id.tasks.ts": {
    id: "routes/api.projects.$id.tasks";
    page: "/api/projects/:id/tasks";
  };
  "routes/api.projects.$id.tasks.$taskId.ts": {
    id: "routes/api.projects.$id.tasks.$taskId";
    page: "/api/projects/:id/tasks/:taskId";
  };
  "routes/api.projects.$id.tasks.$taskId.merge.ts": {
    id: "routes/api.projects.$id.tasks.$taskId.merge";
    page: "/api/projects/:id/tasks/:taskId/merge";
  };
  "routes/api.projects.$id.tasks.$taskId.cancel.ts": {
    id: "routes/api.projects.$id.tasks.$taskId.cancel";
    page: "/api/projects/:id/tasks/:taskId/cancel";
  };
  "routes/api.projects.$id.tasks.$taskId.attachments.ts": {
    id: "routes/api.projects.$id.tasks.$taskId.attachments";
    page: "/api/projects/:id/tasks/:taskId/attachments";
  };
  "routes/api.environments.ts": {
    id: "routes/api.environments";
    page: "/api/environments";
  };
  "routes/api.environments.sync.ts": {
    id: "routes/api.environments.sync";
    page: "/api/environments/sync";
  };
  "routes/api.environments.$id.ts": {
    id: "routes/api.environments.$id";
    page: "/api/environments/:id";
  };
  "routes/api.environments.$id.claude.ts": {
    id: "routes/api.environments.$id.claude";
    page: "/api/environments/:id/claude";
  };
  "routes/api.environments.$id.secrets.ts": {
    id: "routes/api.environments.$id.secrets";
    page: "/api/environments/:id/secrets";
  };
  "routes/api.environments.$id.vercel-sync.ts": {
    id: "routes/api.environments.$id.vercel-sync";
    page: "/api/environments/:id/vercel-sync";
  };
  "routes/api.environments.$id.sandbox.ts": {
    id: "routes/api.environments.$id.sandbox";
    page: "/api/environments/:id/sandbox";
  };
  "routes/api.sandbox.callback.ts": {
    id: "routes/api.sandbox.callback";
    page: "/api/sandbox/callback";
  };
  "routes/api.environments.$id.workspaces.$workspaceId.logs.ts": {
    id: "routes/api.environments.$id.workspaces.$workspaceId.logs";
    page: "/api/environments/:id/workspaces/:workspaceId/logs";
  };
  "routes/api.databases.ts": {
    id: "routes/api.databases";
    page: "/api/databases";
  };
  "routes/api.environments.$id.status.ts": {
    id: "routes/api.environments.$id.status";
    page: "/api/environments/:id/status";
  };
  "routes/api.environments.$id.tasks.ts": {
    id: "routes/api.environments.$id.tasks";
    page: "/api/environments/:id/tasks";
  };
  "routes/api.environments.$id.tasks.$taskId.ts": {
    id: "routes/api.environments.$id.tasks.$taskId";
    page: "/api/environments/:id/tasks/:taskId";
  };
  "routes/api.environments.$id.tasks.$taskId.merge.ts": {
    id: "routes/api.environments.$id.tasks.$taskId.merge";
    page: "/api/environments/:id/tasks/:taskId/merge";
  };
  "routes/api.environments.$id.tasks.$taskId.cancel.ts": {
    id: "routes/api.environments.$id.tasks.$taskId.cancel";
    page: "/api/environments/:id/tasks/:taskId/cancel";
  };
  "routes/api.environments.$id.tasks.$taskId.delete.ts": {
    id: "routes/api.environments.$id.tasks.$taskId.delete";
    page: "/api/environments/:id/tasks/:taskId/delete";
  };
  "routes/api.environments.$id.tasks.$taskId.attachments.ts": {
    id: "routes/api.environments.$id.tasks.$taskId.attachments";
    page: "/api/environments/:id/tasks/:taskId/attachments";
  };
  "routes/api.tasks.ts": {
    id: "routes/api.tasks";
    page: "/api/tasks";
  };
  "routes/api.environments.$id.deployments.ts": {
    id: "routes/api.environments.$id.deployments";
    page: "/api/environments/:id/deployments";
  };
  "routes/api.vercel.environments.ts": {
    id: "routes/api.vercel.environments";
    page: "/api/vercel/environments";
  };
  "routes/api.github.repos.ts": {
    id: "routes/api.github.repos";
    page: "/api/github/repos";
  };
  "routes/api.integrations.github.start.ts": {
    id: "routes/api.integrations.github.start";
    page: "/api/integrations/github/start";
  };
  "routes/api.integrations.github.ts": {
    id: "routes/api.integrations.github";
    page: "/api/integrations/github";
  };
  "routes/api.integrations.vercel.start.ts": {
    id: "routes/api.integrations.vercel.start";
    page: "/api/integrations/vercel/start";
  };
  "routes/api.integrations.vercel.callback.ts": {
    id: "routes/api.integrations.vercel.callback";
    page: "/api/integrations/vercel/callback";
  };
  "routes/api.integrations.vercel.ts": {
    id: "routes/api.integrations.vercel";
    page: "/api/integrations/vercel";
  };
  "routes/api.integrations.status.ts": {
    id: "routes/api.integrations.status";
    page: "/api/integrations/status";
  };
  "routes/api.claude-key.ts": {
    id: "routes/api.claude-key";
    page: "/api/claude-key";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/privacy": typeof import("./app/routes/privacy.tsx");
  "routes/terms": typeof import("./app/routes/terms.tsx");
  "routes/company": typeof import("./app/routes/company.tsx");
  "routes/early-access": typeof import("./app/routes/early-access.tsx");
  "routes/onboarding": typeof import("./app/routes/onboarding.tsx");
  "routes/cli.authorize": typeof import("./app/routes/cli.authorize.tsx");
  "routes/_auth": typeof import("./app/routes/_auth.tsx");
  "routes/_auth.environments": typeof import("./app/routes/_auth.environments.tsx");
  "routes/_auth.environments.new": typeof import("./app/routes/_auth.environments.new.tsx");
  "routes/_auth.environments.$id_.settings": typeof import("./app/routes/_auth.environments.$id_.settings.tsx");
  "routes/_auth.environments.$id_.deploys": typeof import("./app/routes/_auth.environments.$id_.deploys.tsx");
  "routes/_auth.environments.$id_.tasks.$taskId": typeof import("./app/routes/_auth.environments.$id_.tasks.$taskId.tsx");
  "routes/_auth.settings": typeof import("./app/routes/_auth.settings.tsx");
  "routes/_auth.data": typeof import("./app/routes/_auth.data.tsx");
  "routes/_auth.billing": typeof import("./app/routes/_auth.billing.tsx");
  "routes/_auth.inbox": typeof import("./app/routes/_auth.inbox.tsx");
  "routes/_auth.tasks": typeof import("./app/routes/_auth.tasks.tsx");
  "routes/_auth.sessions": typeof import("./app/routes/_auth.sessions.tsx");
  "routes/_auth.teams": typeof import("./app/routes/_auth.teams.tsx");
  "routes/_auth.projects.$id": typeof import("./app/routes/_auth.projects.$id.tsx");
  "routes/api.auth.invite": typeof import("./app/routes/api.auth.invite.ts");
  "routes/api.auth.login.$provider": typeof import("./app/routes/api.auth.login.$provider.ts");
  "routes/api.auth.callback.$provider": typeof import("./app/routes/api.auth.callback.$provider.ts");
  "routes/api.auth.me": typeof import("./app/routes/api.auth.me.ts");
  "routes/api.auth.profile": typeof import("./app/routes/api.auth.profile.ts");
  "routes/api.auth.logout": typeof import("./app/routes/api.auth.logout.ts");
  "routes/api.auth.tokens": typeof import("./app/routes/api.auth.tokens.ts");
  "routes/api.orgs": typeof import("./app/routes/api.orgs.ts");
  "routes/api.orgs.members": typeof import("./app/routes/api.orgs.members.ts");
  "routes/api.projects": typeof import("./app/routes/api.projects.ts");
  "routes/api.projects.$id.tasks": typeof import("./app/routes/api.projects.$id.tasks.ts");
  "routes/api.projects.$id.tasks.$taskId": typeof import("./app/routes/api.projects.$id.tasks.$taskId.ts");
  "routes/api.projects.$id.tasks.$taskId.merge": typeof import("./app/routes/api.projects.$id.tasks.$taskId.merge.ts");
  "routes/api.projects.$id.tasks.$taskId.cancel": typeof import("./app/routes/api.projects.$id.tasks.$taskId.cancel.ts");
  "routes/api.projects.$id.tasks.$taskId.attachments": typeof import("./app/routes/api.projects.$id.tasks.$taskId.attachments.ts");
  "routes/api.environments": typeof import("./app/routes/api.environments.ts");
  "routes/api.environments.sync": typeof import("./app/routes/api.environments.sync.ts");
  "routes/api.environments.$id": typeof import("./app/routes/api.environments.$id.ts");
  "routes/api.environments.$id.claude": typeof import("./app/routes/api.environments.$id.claude.ts");
  "routes/api.environments.$id.secrets": typeof import("./app/routes/api.environments.$id.secrets.ts");
  "routes/api.environments.$id.vercel-sync": typeof import("./app/routes/api.environments.$id.vercel-sync.ts");
  "routes/api.environments.$id.sandbox": typeof import("./app/routes/api.environments.$id.sandbox.ts");
  "routes/api.sandbox.callback": typeof import("./app/routes/api.sandbox.callback.ts");
  "routes/api.environments.$id.workspaces.$workspaceId.logs": typeof import("./app/routes/api.environments.$id.workspaces.$workspaceId.logs.ts");
  "routes/api.databases": typeof import("./app/routes/api.databases.ts");
  "routes/api.environments.$id.status": typeof import("./app/routes/api.environments.$id.status.ts");
  "routes/api.environments.$id.tasks": typeof import("./app/routes/api.environments.$id.tasks.ts");
  "routes/api.environments.$id.tasks.$taskId": typeof import("./app/routes/api.environments.$id.tasks.$taskId.ts");
  "routes/api.environments.$id.tasks.$taskId.merge": typeof import("./app/routes/api.environments.$id.tasks.$taskId.merge.ts");
  "routes/api.environments.$id.tasks.$taskId.cancel": typeof import("./app/routes/api.environments.$id.tasks.$taskId.cancel.ts");
  "routes/api.environments.$id.tasks.$taskId.delete": typeof import("./app/routes/api.environments.$id.tasks.$taskId.delete.ts");
  "routes/api.environments.$id.tasks.$taskId.attachments": typeof import("./app/routes/api.environments.$id.tasks.$taskId.attachments.ts");
  "routes/api.tasks": typeof import("./app/routes/api.tasks.ts");
  "routes/api.environments.$id.deployments": typeof import("./app/routes/api.environments.$id.deployments.ts");
  "routes/api.vercel.environments": typeof import("./app/routes/api.vercel.environments.ts");
  "routes/api.github.repos": typeof import("./app/routes/api.github.repos.ts");
  "routes/api.integrations.github.start": typeof import("./app/routes/api.integrations.github.start.ts");
  "routes/api.integrations.github": typeof import("./app/routes/api.integrations.github.ts");
  "routes/api.integrations.vercel.start": typeof import("./app/routes/api.integrations.vercel.start.ts");
  "routes/api.integrations.vercel.callback": typeof import("./app/routes/api.integrations.vercel.callback.ts");
  "routes/api.integrations.vercel": typeof import("./app/routes/api.integrations.vercel.ts");
  "routes/api.integrations.status": typeof import("./app/routes/api.integrations.status.ts");
  "routes/api.claude-key": typeof import("./app/routes/api.claude-key.ts");
};