// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/onboarding": {
    params: {};
  };
  "/cli/authorize": {
    params: {};
  };
  "/projects": {
    params: {};
  };
  "/projects/new": {
    params: {};
  };
  "/projects/:id": {
    params: {
      "id": string;
    };
  };
  "/settings": {
    params: {};
  };
  "/api/auth/login/:provider": {
    params: {
      "provider": string;
    };
  };
  "/api/auth/callback/:provider": {
    params: {
      "provider": string;
    };
  };
  "/api/auth/me": {
    params: {};
  };
  "/api/auth/logout": {
    params: {};
  };
  "/api/auth/tokens": {
    params: {};
  };
  "/api/orgs": {
    params: {};
  };
  "/api/orgs/members": {
    params: {};
  };
  "/api/projects": {
    params: {};
  };
  "/api/projects/sync": {
    params: {};
  };
  "/api/projects/:id": {
    params: {
      "id": string;
    };
  };
  "/api/projects/:id/claude": {
    params: {
      "id": string;
    };
  };
  "/api/projects/:id/secrets": {
    params: {
      "id": string;
    };
  };
  "/api/projects/:id/sandbox": {
    params: {
      "id": string;
    };
  };
  "/api/vercel/projects": {
    params: {};
  };
  "/api/github/repos": {
    params: {};
  };
  "/api/integrations/github/start": {
    params: {};
  };
  "/api/integrations/github": {
    params: {};
  };
  "/api/integrations/vercel/start": {
    params: {};
  };
  "/api/integrations/vercel/callback": {
    params: {};
  };
  "/api/integrations/vercel": {
    params: {};
  };
  "/api/integrations/status": {
    params: {};
  };
  "/api/claude-key": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/onboarding" | "/cli/authorize" | "/projects" | "/projects/new" | "/projects/:id" | "/settings" | "/api/auth/login/:provider" | "/api/auth/callback/:provider" | "/api/auth/me" | "/api/auth/logout" | "/api/auth/tokens" | "/api/orgs" | "/api/orgs/members" | "/api/projects" | "/api/projects/sync" | "/api/projects/:id" | "/api/projects/:id/claude" | "/api/projects/:id/secrets" | "/api/projects/:id/sandbox" | "/api/vercel/projects" | "/api/github/repos" | "/api/integrations/github/start" | "/api/integrations/github" | "/api/integrations/vercel/start" | "/api/integrations/vercel/callback" | "/api/integrations/vercel" | "/api/integrations/status" | "/api/claude-key";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/onboarding.tsx": {
    id: "routes/onboarding";
    page: "/onboarding";
  };
  "routes/cli.authorize.tsx": {
    id: "routes/cli.authorize";
    page: "/cli/authorize";
  };
  "routes/_auth.tsx": {
    id: "routes/_auth";
    page: "/" | "/projects" | "/projects/new" | "/projects/:id" | "/settings";
  };
  "routes/_auth.dashboard.tsx": {
    id: "routes/_auth.dashboard";
    page: "/";
  };
  "routes/_auth.projects.tsx": {
    id: "routes/_auth.projects";
    page: "/projects";
  };
  "routes/_auth.projects.new.tsx": {
    id: "routes/_auth.projects.new";
    page: "/projects/new";
  };
  "routes/_auth.projects.$id.tsx": {
    id: "routes/_auth.projects.$id";
    page: "/projects/:id";
  };
  "routes/_auth.settings.tsx": {
    id: "routes/_auth.settings";
    page: "/settings";
  };
  "routes/api.auth.login.$provider.ts": {
    id: "routes/api.auth.login.$provider";
    page: "/api/auth/login/:provider";
  };
  "routes/api.auth.callback.$provider.ts": {
    id: "routes/api.auth.callback.$provider";
    page: "/api/auth/callback/:provider";
  };
  "routes/api.auth.me.ts": {
    id: "routes/api.auth.me";
    page: "/api/auth/me";
  };
  "routes/api.auth.logout.ts": {
    id: "routes/api.auth.logout";
    page: "/api/auth/logout";
  };
  "routes/api.auth.tokens.ts": {
    id: "routes/api.auth.tokens";
    page: "/api/auth/tokens";
  };
  "routes/api.orgs.ts": {
    id: "routes/api.orgs";
    page: "/api/orgs";
  };
  "routes/api.orgs.members.ts": {
    id: "routes/api.orgs.members";
    page: "/api/orgs/members";
  };
  "routes/api.projects.ts": {
    id: "routes/api.projects";
    page: "/api/projects";
  };
  "routes/api.projects.sync.ts": {
    id: "routes/api.projects.sync";
    page: "/api/projects/sync";
  };
  "routes/api.projects.$id.ts": {
    id: "routes/api.projects.$id";
    page: "/api/projects/:id";
  };
  "routes/api.projects.$id.claude.ts": {
    id: "routes/api.projects.$id.claude";
    page: "/api/projects/:id/claude";
  };
  "routes/api.projects.$id.secrets.ts": {
    id: "routes/api.projects.$id.secrets";
    page: "/api/projects/:id/secrets";
  };
  "routes/api.projects.$id.sandbox.ts": {
    id: "routes/api.projects.$id.sandbox";
    page: "/api/projects/:id/sandbox";
  };
  "routes/api.vercel.projects.ts": {
    id: "routes/api.vercel.projects";
    page: "/api/vercel/projects";
  };
  "routes/api.github.repos.ts": {
    id: "routes/api.github.repos";
    page: "/api/github/repos";
  };
  "routes/api.integrations.github.start.ts": {
    id: "routes/api.integrations.github.start";
    page: "/api/integrations/github/start";
  };
  "routes/api.integrations.github.ts": {
    id: "routes/api.integrations.github";
    page: "/api/integrations/github";
  };
  "routes/api.integrations.vercel.start.ts": {
    id: "routes/api.integrations.vercel.start";
    page: "/api/integrations/vercel/start";
  };
  "routes/api.integrations.vercel.callback.ts": {
    id: "routes/api.integrations.vercel.callback";
    page: "/api/integrations/vercel/callback";
  };
  "routes/api.integrations.vercel.ts": {
    id: "routes/api.integrations.vercel";
    page: "/api/integrations/vercel";
  };
  "routes/api.integrations.status.ts": {
    id: "routes/api.integrations.status";
    page: "/api/integrations/status";
  };
  "routes/api.claude-key.ts": {
    id: "routes/api.claude-key";
    page: "/api/claude-key";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/onboarding": typeof import("./app/routes/onboarding.tsx");
  "routes/cli.authorize": typeof import("./app/routes/cli.authorize.tsx");
  "routes/_auth": typeof import("./app/routes/_auth.tsx");
  "routes/_auth.dashboard": typeof import("./app/routes/_auth.dashboard.tsx");
  "routes/_auth.projects": typeof import("./app/routes/_auth.projects.tsx");
  "routes/_auth.projects.new": typeof import("./app/routes/_auth.projects.new.tsx");
  "routes/_auth.projects.$id": typeof import("./app/routes/_auth.projects.$id.tsx");
  "routes/_auth.settings": typeof import("./app/routes/_auth.settings.tsx");
  "routes/api.auth.login.$provider": typeof import("./app/routes/api.auth.login.$provider.ts");
  "routes/api.auth.callback.$provider": typeof import("./app/routes/api.auth.callback.$provider.ts");
  "routes/api.auth.me": typeof import("./app/routes/api.auth.me.ts");
  "routes/api.auth.logout": typeof import("./app/routes/api.auth.logout.ts");
  "routes/api.auth.tokens": typeof import("./app/routes/api.auth.tokens.ts");
  "routes/api.orgs": typeof import("./app/routes/api.orgs.ts");
  "routes/api.orgs.members": typeof import("./app/routes/api.orgs.members.ts");
  "routes/api.projects": typeof import("./app/routes/api.projects.ts");
  "routes/api.projects.sync": typeof import("./app/routes/api.projects.sync.ts");
  "routes/api.projects.$id": typeof import("./app/routes/api.projects.$id.ts");
  "routes/api.projects.$id.claude": typeof import("./app/routes/api.projects.$id.claude.ts");
  "routes/api.projects.$id.secrets": typeof import("./app/routes/api.projects.$id.secrets.ts");
  "routes/api.projects.$id.sandbox": typeof import("./app/routes/api.projects.$id.sandbox.ts");
  "routes/api.vercel.projects": typeof import("./app/routes/api.vercel.projects.ts");
  "routes/api.github.repos": typeof import("./app/routes/api.github.repos.ts");
  "routes/api.integrations.github.start": typeof import("./app/routes/api.integrations.github.start.ts");
  "routes/api.integrations.github": typeof import("./app/routes/api.integrations.github.ts");
  "routes/api.integrations.vercel.start": typeof import("./app/routes/api.integrations.vercel.start.ts");
  "routes/api.integrations.vercel.callback": typeof import("./app/routes/api.integrations.vercel.callback.ts");
  "routes/api.integrations.vercel": typeof import("./app/routes/api.integrations.vercel.ts");
  "routes/api.integrations.status": typeof import("./app/routes/api.integrations.status.ts");
  "routes/api.claude-key": typeof import("./app/routes/api.claude-key.ts");
};